services:
  postgres:
    image: postgres:16-alpine
    container_name: xchangemakers-db
    restart: unless-stopped
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: xchangemakers
      POSTGRES_PASSWORD: xchangemakers
      POSTGRES_DB: xchangemakers
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
